name: breaking_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_bloc: ^7.2.0
  flutter_offline: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
